/*
 * MySwingClass.java
 *
 * Created on __DATE__, __TIME__
 */

package com.qiufl;

/**
 *
 * @author  __USER__
 */
public class MySwingClass extends javax.swing.JFrame {

	/** Creates new form MySwingClass */
	public MySwingClass() {
		initComponents();
		//fdfdfd
	}

	/** This method is called from within the constructor to
	 * initialize the form.
	 * WARNING: Do NOT modify this code. The content of this method is
	 * always regenerated by the Form Editor.
	 */
	//GEN-BEGIN:initComponents
	// <editor-fold defaultstate="collapsed" desc="Generated Code">
	private void initComponents() {

		textField1 = new java.awt.TextField();
		jButton1 = new javax.swing.JButton();

		setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
		setTitle("\u5217\u53d8\u884c\u5c0f\u5de5\u5177");

		textField1.setText("\u8bf7\u8f93\u5165\u6570\u636e\u5217");
		textField1.addActionListener(new java.awt.event.ActionListener() {
			public void actionPerformed(java.awt.event.ActionEvent evt) {
				textField1ActionPerformed(evt);
			}
		});

		jButton1.setText("\u786e\u8ba4");

		javax.swing.GroupLayout layout = new javax.swing.GroupLayout(
				getContentPane());
		getContentPane().setLayout(layout);
		layout
				.setHorizontalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								layout
										.createSequentialGroup()
										.addGroup(
												layout
														.createParallelGroup(
																javax.swing.GroupLayout.Alignment.LEADING)
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addGap(
																				166,
																				166,
																				166)
																		.addComponent(
																				jButton1))
														.addGroup(
																layout
																		.createSequentialGroup()
																		.addContainerGap()
																		.addComponent(
																				textField1,
																				javax.swing.GroupLayout.PREFERRED_SIZE,
																				372,
																				javax.swing.GroupLayout.PREFERRED_SIZE)))
										.addContainerGap(18, Short.MAX_VALUE)));
		layout
				.setVerticalGroup(layout
						.createParallelGroup(
								javax.swing.GroupLayout.Alignment.LEADING)
						.addGroup(
								javax.swing.GroupLayout.Alignment.TRAILING,
								layout
										.createSequentialGroup()
										.addGap(20, 20, 20)
										.addComponent(
												textField1,
												javax.swing.GroupLayout.PREFERRED_SIZE,
												152,
												javax.swing.GroupLayout.PREFERRED_SIZE)
										.addPreferredGap(
												javax.swing.LayoutStyle.ComponentPlacement.RELATED,
												34, Short.MAX_VALUE)
										.addComponent(jButton1).addGap(69, 69,
												69)));

		pack();
	}// </editor-fold>
	//GEN-END:initComponents

	private void textField1ActionPerformed(java.awt.event.ActionEvent evt) {
		// TODO add your handling code here:
	}

	/**
	 * @param args the command line arguments
	 */
	public static void main(String args[]) {
		java.awt.EventQueue.invokeLater(new Runnable() {
			public void run() {
				new MySwingClass().setVisible(true);
			}
		});
	}

	//GEN-BEGIN:variables
	// Variables declaration - do not modify
	private javax.swing.JButton jButton1;
	private java.awt.TextField textField1;
	// End of variables declaration//GEN-END:variables

}
